name: ci

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: build
        run: |
          docker compose build

      - name: test
        run: |
          docker compose run rust cargo test
