name: ci

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Make docker container
        run: |
          docker compose up -d

      - name: Test
        run: |
          docker compose run -T rust cargo test -- --show-output
